version: '3.4'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB_NAME: nest
    networks:
      - samPersonal
networks:
  samPersonal:
